version: '3'
services:
  php-fpm:
    build: ./docker/php
    image: jefffrade/tracking-api:php-fpm
    restart: on-failure
    container_name: tracking-api-php-fpm
    command: php-fpm
    links:
        - mysql
    volumes:
      - ./:/tracking-api
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 9000 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  nginx:
    build: ./docker/nginx
    image: jefffrade/tracking-api:nginx
    restart: on-failure
    container_name: tracking-api-nginx
    command: nginx -g "daemon off;"
    links:
      - php-fpm
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./:/tracking-api
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 80 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  mysql:
    build: ./docker/mysql
    image: jefffrade/tracking-api:mysql
    restart: on-failure
    container_name: tracking-api-mysql
    volumes:
      - "${DOCKER_DATA_PATH}/mysql:/var/lib/mysql"
    command:
      - "--innodb_use_native_aio=0"
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 3306 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2
